In [14]:
import pandas as pd

price_raw = pd.read_excel('Daily물가지수.xlsx', sheet_name='p', skiprows=13, index_col=0).iloc[6:]
price_raw.index = pd.to_datetime(price_raw.index)
price_raw

# 칼럼명에 -US 접두사 다 지우기
price_raw.columns = price_raw.columns.str.replace('-US', '')
price_raw.to_csv('price_raw.csv')

In [16]:
price_raw.columns

Index(['AAPL', 'ABBV', 'ABT', 'ACGL', 'ACN', 'ADBE', 'ADI', 'ADM', 'ADP',
       'ADSK',
       ...
       'WST', 'WYNN', 'WY', 'XEL', 'XOM', 'XYL', 'YUM', 'ZBH', 'ZBRA', 'ZTS'],
      dtype='object', length=456)

In [19]:
# yfinance 로 주가 데이터 가져오기, price_raw 칼럼 이용
import yfinance as yf
stock_data = yf.download(list(price_raw.columns), start='2000-01-01', end='2025-03-24')

# BRK.B, BF.B 는 BRK-B, BF-B 로 변경되었으므로 다시 다운로드 하여 병합

temp_data = yf.download(['BRK-B', 'BF-B'], start='2000-01-01', end='2025-03-24')
temp_data

# 날짜 기준으로 병합하고 종가만 남기기
stock_data = pd.concat([stock_data, temp_data], axis=1)
stock_data = stock_data[['Close']]
stock_data

[*********************100%***********************]  456 of 456 completed

2 Failed downloads:
['BRK.B']: YFTzMissingError('possibly delisted; no timezone found')
['BF.B']: YFPricesMissingError('possibly delisted; no price data found  (1d 2000-01-01 -> 2025-03-24)')
[*********************100%***********************]  2 of 2 completed

Price            Close                                                 \
Ticker               A        AAPL        ABBV         ABT       ACGL
Date
2000-01-03   43.382843    0.842151         NaN    8.244916   1.215037
2000-01-04   40.068863    0.771149         NaN    8.009346   1.208433
2000-01-05   37.583393    0.782433         NaN    7.994625   1.320692
2000-01-06   36.152374    0.714723         NaN    8.274363   1.307485
2000-01-07   39.165070    0.748578         NaN    8.362698   1.380124
...                ...         ...         ...         ...        ...
2025-03-17  122.489998  214.000000  214.470001  127.639999  95.279999
2025-03-18  123.099998  212.690002  213.850006  126.300003  93.300003
2025-03-19  122.209999  215.240005  212.250000  127.419998  93.190002
2025-03-20  120.279999  214.100006  211.960007  126.779999  92.449997
2025-03-21  120.750000  218.270004  210.009995  126.339996  91.980003

Price                                                                  ...  \
Ticker             ACN        ADBE         ADI        ADM         ADP  ...
Date                                                                   ...
2000-01-03         NaN   16.274675   27.973967   6.179295   24.210934  ...
2000-01-04         NaN   14.909399   26.558813   6.114927   24.210934  ...
2000-01-05         NaN   15.204175   26.946522   6.018377   23.978146  ...
2000-01-06         NaN   15.328288   26.209858   6.050560   24.298246  ...
2000-01-07         NaN   16.072985   26.946522   6.147110   24.851131  ...
...                ...         ...         ...        ...         ...  ...
2025-03-17  325.709991  399.339996  211.679993  47.990002  296.579987  ...
2025-03-18  324.070007  391.369995  209.160004  47.680000  295.929993  ...
2025-03-19  324.470001  387.890015  209.970001  46.930000  298.790009  ...
2025-03-20  300.910004  389.609985  205.899994  46.520000  297.510010  ...
2025-03-21  305.320007  387.260010  204.399994  46.099998  295.320007  ...

Price                                                                 \
Ticker           WYNN        XEL         XOM         XYL         YUM
Date
2000-01-03        NaN   6.735728   17.730228         NaN    4.590249
2000-01-04        NaN   6.890822   17.390627         NaN    4.497984
2000-01-05        NaN   7.156708   18.338696         NaN    4.521049
2000-01-06        NaN   7.090239   19.286757         NaN    4.482605
2000-01-07        NaN   7.090239   19.230154         NaN    4.382649
...               ...        ...         ...         ...         ...
2025-03-17  86.419998  69.959999  113.760002  123.080002  157.130005
2025-03-18  85.430000  70.279999  113.639999  120.919998  157.300003
2025-03-19  85.050003  70.239998  115.410004  121.309998  157.509995
2025-03-20  83.070000  70.089996  115.900002  119.839996  157.889999
2025-03-21  82.629997  69.110001  115.500000  118.470001  156.750000

Price
Ticker             ZBH        ZBRA         ZTS       BF-B       BRK-B
Date
2000-01-03         NaN   25.027779         NaN   3.766967   35.299999
2000-01-04         NaN   24.666668         NaN   3.697510   34.080002
2000-01-05         NaN   25.138889         NaN   3.726110   34.639999
2000-01-06         NaN   23.777779         NaN   3.750624   36.080002
2000-01-07         NaN   23.513889         NaN   3.791482   36.400002
...                ...         ...         ...        ...         ...
2025-03-17  111.790001  285.269989  165.169998  35.770000  523.010010
2025-03-18  112.879997  282.579987  164.429993  35.290001  523.140015
2025-03-19  112.910004  285.829987  163.750000  34.860001  525.270020
2025-03-20  111.779999  285.010010  163.160004  34.919998  528.729980
2025-03-21  110.730003  289.989990  163.029999  34.650002  521.909973

[6343 rows x 458 columns]

In [20]:
stock_data.to_csv('stock_data.csv')

In [23]:
stock_data = pd.read_csv('stock_data.csv', index_col=0, parse_dates=True)
stock_data

stock_data_return = stock_data.pct_change()
stock_data_return

stock_data_return.to_csv('stock_data_return.csv')

C:\Users\USER\AppData\Local\Temp\ipykernel_11860\3969573915.py:4: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  stock_data_return = stock_data.pct_change()

In [6]:
cpi_data = pd.read_excel('CPI_dataset.xlsx', index_col=0, parse_dates=True)
cpi_data

# 섹터들 값 없는 행 드롭
cpi_data = cpi_data[cpi_data.notna().all(axis=1)]
cpi_data

,Release,CPI_YOY,GASREGW,DCOILWTICO,XLB,XLC,XLE,XLF,XLI,XLK,XLP,XLRE,XLU,XLV,XLY
date,,,,,,,,,,,,,,,
2018-06-20,False,2.781922,0.207296,-0.018803,-0.003249,0.012410,0.004415,-0.002559,0.000683,0.002100,0.000979,0.010794,0.000797,0.002122,0.004742
2018-06-21,False,2.781922,0.207296,-0.018803,-0.010635,-0.006129,-0.018516,-0.002933,-0.012554,-0.007683,0.001957,0.005967,0.003385,-0.005762,-0.007124
2018-06-22,False,2.781922,0.207296,-0.018803,0.014563,0.004377,0.019951,-0.004779,0.003455,-0.003238,0.008201,0.008742,0.006944,0.004494,-0.001704
2018-06-25,False,2.781922,0.216738,-0.018803,-0.015550,-0.020598,-0.020093,-0.010713,-0.012670,-0.020762,0.005036,-0.002476,0.016552,-0.009184,-0.021739
2018-06-26,False,2.781922,0.216738,-0.018803,0.003819,0.001658,0.012629,-0.003361,0.003766,0.004038,-0.004240,0.005275,0.001163,-0.003090,0.007162
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-17,False,2.814270,-0.095340,-0.174864,0.012561,0.007144,0.015931,0.011748,0.013803,0.006965,0.014589,0.017612,0.004184,0.012696,0.001576
2025-03-18,False,2.814270,-0.095340,-0.174864,-0.001723,-0.013982,0.001645,-0.001222,-0.007974,-0.015225,-0.011404,-0.006164,-0.006944,0.000477,-0.017816
2025-03-19,False,2.814270,-0.095340,-0.115086,0.003337,0.011886,0.016313,0.011014,0.013270,0.013010,0.000000,0.001193,0.003687,0.000545,0.019173
2025-03-20,False,2.814270,-0.095340,-0.115086,-0.006307,-0.002164,0.003663,0.001412,-0.005014,-0.007119,-0.004890,-0.001191,0.004054,0.000613,-0.002383
2025-03-21,False,2.814270,-0.095340,-0.115086,-0.009925,0.007848,-0.006977,-0.003626,-0.005340,0.002718,-0.000378,-0.009781,-0.006435,-0.002789,0.003609

In [12]:
sector_index_tickers = [
    "^SP500-55",  # S&P 500 Utilities Sector
    "^SP500-40",  # S&P 500 Financials Sector
    "^SP500-25",  # S&P 500 Consumer Discretionary Sector
    "^SP500-20",  # S&P 500 Industrials Sector
    "^SP500-15",  # S&P 500 Materials Sector
    "^SP500-1010",  # S&P 500 Energy Sector
    "^SP500-30",  # S&P 500 Consumer Staples Sector
    "^SP500-35",  # S&P 500 Health Care Sector
    "^SP500-45",  # S&P 500 Information Technology Sector
    "^SP500-50",  # S&P 500 Communication Services Sector
    "^SP500-60",  # S&P 500 Real Estate Sector
]

import yfinance as yf

# 섹터들의 주가 데이터 가져오기
sector_indices = yf.download(sector_index_tickers, start='2000-01-01', end='2025-03-24')
sector_indices

# 주가 데이터 정리
sector_indices = sector_indices['Close']
sector_indices.to_csv('sector_indices.csv')
sector_indices

[*********************100%***********************]  11 of 11 completed

Ticker,^SP500-1010,^SP500-15,^SP500-20,^SP500-25,^SP500-30,^SP500-35,^SP500-40,^SP500-45,^SP500-50,^SP500-55,^SP500-60
Date,,,,,,,,,,,
2000-01-03,NaN,157.240005,265.609985,291.390015,204.229996,325.119995,307.200012,829.139893,319.059998,138.750000,NaN
2000-01-04,NaN,154.750000,257.239990,282.750000,201.130005,312.779999,294.540009,783.392090,304.940002,138.910004,NaN
2000-01-05,NaN,160.880005,257.200012,280.070007,201.839996,319.649994,292.559998,775.052612,309.149994,144.080002,NaN
2000-01-06,NaN,165.600006,261.640015,281.279999,204.380005,328.779999,304.089996,744.334045,301.350006,146.089996,NaN
2000-01-07,220.850006,166.970001,270.390015,290.489990,212.880005,354.940002,310.730011,756.653442,301.170013,148.389999,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2025-03-17,691.619995,545.559998,1122.310059,1571.109985,879.799988,1704.959961,814.729980,4181.660156,330.329987,399.859985,261.970001
2025-03-18,693.169983,545.049988,1113.640015,1541.329956,868.390015,1706.979980,813.659973,4112.830078,323.269989,397.239990,260.559998
2025-03-19,704.190002,546.880005,1128.030029,1570.599976,869.440002,1707.239990,822.150024,4171.140137,327.440002,398.410004,260.459991
2025-03-20,707.109985,543.489990,1122.859985,1567.589966,864.909973,1709.160034,823.729980,4150.540039,326.390015,400.059998,260.130005
2025-03-21,702.729980,538.059998,1116.780029,1577.459961,864.150024,1703.969971,820.539978,4171.049805,329.640015,397.429993,257.359985

In [24]:
sector_indices_return = sector_indices.pct_change()
sector_indices_return.to_csv('sector_indices_return.csv')

C:\Users\USER\AppData\Local\Temp\ipykernel_11860\743497136.py:1: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  sector_indices_return = sector_indices.pct_change()

In [13]:
# sector_indices랑 cpi_data 합치기
cpi_data = pd.concat([cpi_data, sector_indices], axis=1)
cpi_data

# cpi_data 저장
cpi_data.to_csv('cpi_data.csv')